version: '3.8'

services:
  bot:
    build: .
    container_name: bot
    network_mode: "host"
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: rabbitmq
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    network_mode: "host"